branches:
  only:
  - "/^v0.*$/"
  - master
language: python
python:
- '3.5'
cache: pip
install:
- pip install --upgrade pip
- pip install --upgrade -r requirements.txt

sudo: required 
dist: trusty 
group: deprecated-2017Q4

addons:
  postgresql: '9.4'
before_script:
- mv configs/settings_deployment_test.py councilmatic/settings_deployment.py
- mv configs/test_config_deployment.py tests/test_config.py
script:
- python manage.py migrate
- pytest
deploy:
  - provider: codedeploy
    access_key_id: AKIAJNYGDLOJKHOUWCAA
    secret_access_key:
      secure: Li3Vm/04cHNGF5Bnuh293no+BjKyPcrll7soBu20mKIL5e93lo5g8pJBgIIgxvG9os+0dFy7ehb07FOMNtX4+DlpG2OIFfMnhUiq2YAgwK7emdQtYVnw4D2EuubuflHia81p/0/6CmBugnI1COPIRfBF8FzZmU26xb/dtmljpq79TVCRHuswphQBaQzqxPHndhjgD71HeRTQA6WW9yjX/M/Ps5baLHcj2nKABIZzxFVUK+07QuRymAiWnavMxqMC5XGDpSNnErRT+GolGB9kehwtk1ra1tNU6Tw9BzxjYy4q6Lfpz2b9vZdMjETpSt8FOJr8bWr+V6XN6PF7bv44641SsaGyytaNSCEOtvyeZeMQm5PjwkeWZN2heL2lc7F/cL0DmyI3svltSG2vFIqlQu5VnQqQ2OrVel4dadP86w7Tv+1Cel7KFOGJxx7waUEqTvGy92WzY7IuAx348gIbzGOQ7WsuOLEVDC6SjY06SpvRU69I3eMFXjoN4T7SPxHb+XF3vj6yZbE0iLocAYCA/VNJ/6Tdee0ZSwZ726vpsmBMDcSBEyvkvfqTrwl8xKsViabMaAnHsuQdo2VJG2FJy2mzcGFgcMtR6/SdQ+PIiSh0FGl2wEegiSRCjTquAD8E6KxZRzQhm6b48aRmUyG70x8iLiSSTSQAo1Ui8vyw/RM=
    application: nyc-council-councilmatic
    deployment_group: staging
    on:
      branch: master
  - provider: codedeploy
    access_key_id: AKIAJNYGDLOJKHOUWCAA
    secret_access_key:
      secure: Li3Vm/04cHNGF5Bnuh293no+BjKyPcrll7soBu20mKIL5e93lo5g8pJBgIIgxvG9os+0dFy7ehb07FOMNtX4+DlpG2OIFfMnhUiq2YAgwK7emdQtYVnw4D2EuubuflHia81p/0/6CmBugnI1COPIRfBF8FzZmU26xb/dtmljpq79TVCRHuswphQBaQzqxPHndhjgD71HeRTQA6WW9yjX/M/Ps5baLHcj2nKABIZzxFVUK+07QuRymAiWnavMxqMC5XGDpSNnErRT+GolGB9kehwtk1ra1tNU6Tw9BzxjYy4q6Lfpz2b9vZdMjETpSt8FOJr8bWr+V6XN6PF7bv44641SsaGyytaNSCEOtvyeZeMQm5PjwkeWZN2heL2lc7F/cL0DmyI3svltSG2vFIqlQu5VnQqQ2OrVel4dadP86w7Tv+1Cel7KFOGJxx7waUEqTvGy92WzY7IuAx348gIbzGOQ7WsuOLEVDC6SjY06SpvRU69I3eMFXjoN4T7SPxHb+XF3vj6yZbE0iLocAYCA/VNJ/6Tdee0ZSwZ726vpsmBMDcSBEyvkvfqTrwl8xKsViabMaAnHsuQdo2VJG2FJy2mzcGFgcMtR6/SdQ+PIiSh0FGl2wEegiSRCjTquAD8E6KxZRzQhm6b48aRmUyG70x8iLiSSTSQAo1Ui8vyw/RM=
    application: nyc-council-councilmatic
    deployment_group: production
    on:
      tags: true
