version: '3.3'
services: 
  solr:
    image: solr:7.1.0
    container_name: nyccouncilmatic_solr
    volumes:
      - "${DATA_DIR}:/opt/solr/server/solr/mycores:rw"
      - ./solr_configs:/nyc_configs
    command: sh -c 'solr-precreate nyc-council-councilmatic /nyc_configs'
    expose:
      - "8983"
    ports: 
      - "8983:8983"
    environment:
      SOLR_LOG_LEVEL: ERROR